config/routes.rb
Rails.application.routes.draw do

  namespace :api, constriants: { format: :json } do
    get 'seeds' => 'seeds#all'
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }



  resources :sementes, controller: 'seeds'

  resources :seeds do
  	member do
  		get "like", to: "seeds#like"
  		get "unlike", to: "seeds#unlike"
  	end
  end
  
  resources :terms


  root 'seeds#index'
end

app/models/seed.rb
class Seed < ActiveRecord::Base
	acts_as_votable
	belongs_to :user

	has_attached_file :image, 
					  :styles => { :medium => "300x300>" }, 
					  :default_url => "seed-placeholder.jpg"

	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	

end

app/models/term.rb
class Term < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :seeds

  acts_as_voter

  def self.from_omniauth(auth)
     where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
       user.provider = auth.provider
       user.uid = auth.uid
       user.name = auth.info.name
       user.email = auth.info.email
       user.location = auth.info.location
       user.photo = auth.info.image
       user.password = Devise.friendly_token[0,20]
     end
  end

  

  def online?
    # If key lifetime effused - that returns false, differently true
    if $redis_onlines.exists(self.id)
      "user-online"
    else
      "user-offline"
    end
  end

  

end

app/controllers/api/seeds_controller.rb
module Api
	class Api::SeedsController < ApplicationController

		respond_to :json

		def all
			render json: Seed.all
		end

		def default_serializer_options
			{ root: false }
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  after_action :set_online

  private

  # set to online
  def set_online
    if !!current_user
      #  Wrapper in pipelined for the acceleration, two requests go as one without waiting
      # The answer, usage multi-exec instead of pipelined
      # Does not give such gain in productivity
      $redis_onlines.pipelined do
        # Value is not necessary, the key is necessary only
        $redis_onlines.set(current_user.id, nil)
        # We install key lifetime - 10 minutes, through 10 mine a key to be deleted
        $redis_onlines.expire(current_user.id, 10*60)
      end
    end
  end


end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    def facebook
        @user = User.from_omniauth(request.env["omniauth.auth"])
        sign_in_and_redirect @user
    end
end

app/controllers/seeds_controller.rb
class SeedsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_seed, only: [:show, :edit, :update, :destroy, :upvote]

  def index
    @seeds = Seed.all.order("created_at DESC")
  end

  def show

  end

  def new
    @seed = current_user.seeds.build
  end

  def create
    @seed = current_user.seeds.build(seed_params)

    if @seed.save
      redirect_to @seed, notice: "Semente criada com sucesso."
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @seed.update(seed_params)
      redirect_to @seed, notice: "Semente atualizada com sucesso."
    else
      render 'edit'
    end
  end

  def destroy
    @seed.destroy
		redirect_to root_path
  end

  def like
    @seed = Seed.find(params[:id])
    @seed.liked_by current_user
    respond_to do |format|
      format.html { redirect_to :back }
      format.js { render layout: false }
    end
  end

  def unlike
    @seed = Seed.find(params[:id])
    @seed.unliked_by current_user
    respond_to do |format|
      format.html { redirect_to :back }
      format.js { render layout: false }
    end
  end

  private

  def seed_params
    params.require(:seed).permit(:title, :description, :image, :common_name, :scientific_name, :production_year, :location)
  end

  def find_seed
    @seed = Seed.find(params[:id])
  end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
	def index
		
	end
end

app/helpers/api/seeds_helper.rb
module Api::SeedsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def cp(path)
	  "current" if current_page?(path)
	end

	def users_online
	  $redis_onlines.keys.count
	  # => ["123", "234", "1", "23"]
	  # Returns an array with id online of users
	end


	def current_user_photo
		if current_user.photo
			image_tag current_user.photo
		else
			image_tag("avatar-placeholder.jpg")
		end
	end

	def user_liked
		if current_user.voted_for? @seed
			"liked"
		end
	end

	def nav_fixed
		if current_page?(controller: '/seeds', action: 'index') || current_page?(root_path)
			"fixed"
		end
	end
end

app/helpers/seeds_helper.rb
module SeedsHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Troca de Sementes</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- TODO 

  Facebook OG meta tags

  -->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <script src="//use.typekit.net/zgd8tfc.js"></script>
  <script>try{Typekit.load();}catch(e){}</script>
</head>
<body>
	<main>
    <%= render 'partials/navbar' %>

     <% flash.each do |name, msg| %>
       <%= content_tag :div, msg, class: "alert alert-green" %>
     <% end %>
     <%= yield %> 
  </main>

  <%= render 'partials/footer' %>
</body>

app/views/partials/_footer.html.erb
<footer>
	<div class="container">
		<div class="footer-content">
			<%= image_tag("logo_bw.svg", size: "53x80", alt: "Logo") %>
			<a class="logo-domain" href="#">trocadesementes.pt</a>
			<p>Desenvolvido por <a href="http://tiansial.com/" target="_blank">Tiago Almeida</a></p>
		</div>
	</div>
</footer>

app/views/partials/_likebutton.html.erb
<li class="likes">
 <!--  <% if current_user.liked? seed %>
    <%= link_to unlike_seed_path(seed), method: :get, data: { remote: true }, class: 'unlike_seed' do %>
      <i class="fa fa-heart liked"></i>
  <% end %>
  <% else %>
    <%= link_to like_seed_path(seed), method: :get, data: { remote: true }, class: 'like_seed' do %>
      <i class="fa fa-heart "></i>
  <% end %>
  <% end %> -->

  <% if current_user.liked? seed %>
     <%= link_to unlike_seed_path(seed), method: :get, remote: true, class: 'unlike_seed' do %>
         <i class="fa fa-heart "></i>
     <% end %>
    <% else %>
    <%= link_to like_seed_path(seed), method: :get, remote: true, class: 'like_seed' do %>
        <i class="fa fa-heart "></i>
    <% end %>
   <% end %>
  <span class="likecount-<%= seed.id %>"><%= seed.get_likes.size  %></span>
</li>

app/views/partials/_navbar.html.erb
<header class="navigation <%= nav_fixed %>" role="banner">
  <div class="navigation-wrapper">
    <a href="<%= root_path %>" class="logo">
      <%= image_tag("logo_color.svg", size: "53x80", alt: "Logo") %>
    </a>
    <a href="<%= root_path %>" class="logo-domain">trocadesementes.pt</a>
    <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu"><i class="fa fa-bars"></i></a>
    <nav role="navigation">
      <ul id="js-navigation-menu" class="navigation-menu show">
        <% if user_signed_in? %>
          <li class="nav-link"><%= link_to "Sementes", sementes_path, class: cp(sementes_path) %></li>
          <li class="nav-link"><a href="#">Hortas Comunitárias</a></li>
          <li class="nav-link"><a href="#">Notícias</a></li>
          <li class="nav-link"><%= link_to "Termos e Condições", terms_path, class: cp(terms_path) %></li>
          <li class="nav-link more"><a href="javascript:void(0)">
            <div class="user--nav_img">
              <div class="heightContainer">
                 <% if current_user.photo %>
                    <%= image_tag current_user.photo %>
                <% else %>
                    <%= image_tag("avatar-placeholder.jpg") %>
                <% end %> 
              </div>
            </div>
            <%= current_user.name %></a>
             <ul class="submenu">
               <li><%= link_to "Adicionar Semente", new_semente_path %></li>
               <li><a href="#">Adicionar Desejo</a></li>
               <li><%= link_to "Perfil", edit_user_registration_path %></li>
               <li><%= link_to "Sair", destroy_user_session_path, method: :delete %></li>
             </ul>
          </li>
        <% else %>
          <li class="nav-link"> <%= link_to "Entrar", new_user_session_path %></li>
          <li class="nav-link"> <%= link_to "Registrar", new_user_registration_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/seeds/_form.html.erb
<%= simple_form_for @seed, html: { multipart: true } do |f| %>
  <% if @seed.errors.any? %>
    <div id="errors">
      <h2>
        <%= pluralize(@seed.errors.count, "error") %>
        prevented this Pin from saving
      </h2>
      <ul>
        <% @seed.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.input :common_name, label: 'Nome comum:', input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.input :scientific_name, label: 'Nome científico:', input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.input :description, label: 'Descrição:', input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.input :production_year, label: 'Ano de Produção:', input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.input :location, label: 'Localidade:', input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.input :image, label: 'Imagem:', input_html: { class: 'form-control' } %>
  </div>
  <%= f.button :submit,  class: "btn btn-primary" %>
<% end %>

app/views/seeds/edit.html.erb
<h1>Editar Semente</h1>
<%= render 'form' %>
<%= link_to "Cancelar", seed_path %>

app/views/seeds/index.html.erb
<div class="seeds--wrapper">

  <div class="seeds--interface__wrapper">
    <div class="seeds--search">
      search
    </div>

    <div class="seeds--stats">
      <div class="community">
        <h1>Comunidade</h1>
        <p><i class="fa fa-users"></i> Membros registados: <%= User.count %></p>
        <p class="facebook"><i class="fa fa-thumbs-up"></i> Grupo Facebook: </p>
        <p class="online"><i class="fa fa-circle"></i> Membros online: <%= users_online %></p>
      </div>
    </div>
  </div>

  <div class="seeds-feed_wrapper">
    <div class="seeds--feed transitions-enabled" id="seeds">
      <% @seeds.each do |seed| %>
        <div class="seeds--card">
          <a class="social-share" href="
            https://www.facebook.com/dialog/feed?app_id=1452548131713566&display=popup&caption=An%20example%20caption&link=http%3A%2F%2Flocalhost%3A3000%2Fseeds%2F46&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fseeds
          ">
            <i class="fa fa-share"></i> Facebook
          </a>
          
          <%= link_to (seed) do %>
            <figure>
                <%= image_tag seed.image.url(:medium) %>
            </figure>
          <% end %>

          <div class="seeds--card__content">
            <%= link_to (seed), :class => "seeds--card__type" do %>
              <div>
                <h1><%= seed.common_name %></h1>
                <p><em><%= seed.scientific_name %></em></p>
              </div>
            <% end %>

            <div class="seeds--card__user">

              <a href="#">

                <div class="seeds--card__userimg">
                    <div class="heightContainer">
                       <% if seed.user.photo %>
                          <%= image_tag seed.user.photo %>
                      <% else %>
                          <%= image_tag("avatar-placeholder.jpg") %>
                      <% end %> 
                    </div>
                </div>

                <div class="seeds--card__username">
                  <%= seed.user.name  %>
                </div>

                <div class="seeds--card__userlocation">
                  <%= seed.user.location  %>
                  <p></p>
                </div>

                <span class="seeds--card__userstatus <%= seed.user.online? %>" >
                </span>
              </a>
            </div>

            <div class="seeds--card__popularity">
              <ul>
                <%= render :partial => "partials/likebutton", :locals => {:seed => seed} %>
                
                <li>
                  <a href="#">
                    <a href="#">
                      <i class="fa fa-comment"></i>
                    </a>
                    <span>13</span>
                  </a>
                </li>
              </ul>
            </div>

            <div class="seeds--card__wantbutton">
              <a href="#">quero!</a>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  
</div>

<a href="<%= new_seed_path %>" class="newseed"><i class="fa fa-plus"></i></a>

app/views/seeds/like.js.erb
<!-- $('.like_seed').bind('ajax:success', function(){
   $(this).parent().parent().find('.likecount-<%= @seed.id %>').html('<%= escape_javascript @seed.votes_for.size.to_s %>');
   $(this).closest('.votes').html(' <%= link_to "Unlike", unlike_seed_path(@seed), remote: true, method: :get, class: 'unlike_seed' %>');
}); -->


$('.like_seed').bind('ajax:success', function(){
   $(this).parent().find('.likecount-<%= @seed.id %>').html('<%= escape_javascript @seed.votes_for.size.to_s %>');
   $(this).closest('.like_seed').hide();
   $(this).closest('.likes').html(' <%= link_to "Unlike", unlike_seed_path(@seed), remote: true, method: :get, class: 'unlike_seed' %>');
});

app/views/seeds/new.html.erb
<div class="new--seed_box">
	<h1>Adicionar nova semente</h1>
	<p>Introduza uma semente que tenha para trocar. </p>
	<%= render 'form' %>
	<%= link_to 'Voltar', root_path %>
</div>

app/views/seeds/show.html.erb
<h1>
  <%= @seed.common_name %>
</h1>
<p>
  <%= @seed.description %>
</p>
<p><%= @seed.location  %></p>
<%= image_tag @seed.image.url(:medium) %>
<p><%= @seed.user.email  %></p>
<%= link_to "Voltar", root_path %>

<% if current_user.id == @seed.user_id %>
	<%= 
		link_to "Apagar", seed_path, 
		method: :delete, 
		data: { confirm: "De certeza que quer apagar a #{@seed.common_name}semente?"} 
	%>
	<%= link_to "Editar", edit_seed_path %>
<% end %>

app/views/seeds/unlike.js.erb
<!-- $('.unlike_seed').bind('ajax:success', function(){
   $(this).parent().parent().find('.likecount-<%= @seed.id %>').html('<%= escape_javascript @seed.votes_for.size.to_s %>');
   $(this).closest('.fa-heart').removeClass('liked');
   $(this).closest('.votes').html(' <%= link_to "Like", like_seed_path(@seed), remote: true, method: :get, class: 'like_seed' %>');
}); -->

$('.unlike_seed').bind('ajax:success', function(){
   $(this).parent().find('.likecount-<%= @seed.id %>').html('<%= escape_javascript @seed.votes_for.size.to_s %>');
   $(this).closest('.unlike_seed').hide();
   $(this).closest('.likes').html(' <%= link_to "Like", like_seed_path(@seed), remote: true, method: :get, class: 'like_seed' %>');

});

app/views/terms/index.html.erb
<div class="terms--box">
	<h1>Termos e Condições</h1>
	<p>Bespoke master cleanse typewriter tote bag. Blog keffiyeh banjo Schlitz slow-carb XOXO. Leggings meditation Echo Park VHS Intelligentsia taxidermy master cleanse, lo-fi polaroid plaid brunch direct trade cred tousled. Pinterest art party disrupt, keytar paleo kitsch narwhal deep v. Gastropub lumbersexual occupy cray. Fap bespoke XOXO street art wayfarers, chambray VHS farm-to-table YOLO. Fashion axe literally deep v dreamcatcher farm-to-table VHS occupy.</p>

	<p>Polaroid freegan Truffaut four dollar toast biodiesel you probably haven't heard of them. Sartorial Helvetica Tumblr freegan, 90's roof party raw denim cronut keffiyeh kitsch meggings plaid leggings. Skateboard tousled crucifix, gluten-free shabby chic 8-bit authentic retro. Austin 90's four loko jean shorts lumbersexual High Life distillery, direct trade actually Truffaut Pitchfork pork belly wolf. Kogi Blue Bottle American Apparel wolf keytar, messenger bag ugh skateboard typewriter. Schlitz Etsy drinking vinegar Portland, shabby chic Neutra +1 food truck hashtag. Bushwick Intelligentsia skateboard Portland, iPhone artisan PBR&B heirloom pour-over church-key kogi gluten-free McSweeney's DIY.</p>

	<p>Messenger bag dreamcatcher ugh skateboard next level VHS, church-key selfies cronut listicle American Apparel cornhole gastropub. Salvia organic whatever, PBR&B four dollar toast distillery small batch. Craft beer banjo wolf authentic +1 tilde. Flannel artisan Tumblr chillwave. Vice chambray Helvetica, meditation before they sold out High Life food truck dreamcatcher try-hard photo booth blog Thundercats. Fixie whatever fingerstache, fanny pack lomo iPhone cray Intelligentsia keytar. Neutra banjo freegan four loko, Etsy kogi crucifix Vice cardigan salvia.</p>

	<p>Freegan hella skateboard, Etsy Odd Future fashion axe swag synth. Normcore Truffaut shabby chic bicycle rights selfies. YOLO cornhole master cleanse distillery cray, raw denim normcore. Cold-pressed Helvetica tilde Neutra Intelligentsia, mlkshk pour-over flexitarian pork belly tofu Marfa retro quinoa. Artisan cred messenger bag shabby chic. Flexitarian brunch beard chambray bicycle rights McSweeney's trust fund letterpress post-ironic. Heirloom chillwave slow-carb, you probably haven't heard of them pickled try-hard photo booth Intelligentsia Williamsburg banh mi cardigan PBR&B Marfa Austin asymmetrical.</p>
</div>